name: 'Firefox Addon Action'
description: 'Upload your addon to the Firefox addon store'
author: 'yayuyokitano'
inputs:
  guid: 
    required: true
    description: 'The GUID of your addon'
  api_key: 
    required: true
    description: 'API key to authenticate with'
  api_secret: 
    required: true
    description: 'API secret to authenticate with'
  xpi_path: 
    required: true
    description: 'The path to your XPI file to upload'
  src_path: 
    required: true
    description: 'The path to your XPI file to upload'
runs:
  using: 'node16'
  main: 'dist/index.js'
